Repository kookmin-sw/capstone-2024-08, pull requests merged in 2024-05, with the labels that each got.

#48 [CD-169][CD-170] Chore: 자잘한 옵션 추가
  backend/create_script/config/config.py
  backend/create_script/gpt/__init__.py
  backend/feedback/examples/knnvc_demo.ipynb
  backend/requirements.txt
  front/lib/main.dart
  front/lib/model/load_data.dart
  front/lib/screen/script/create_user_script/adjust_user_script.dart
  front/lib/screen/script/create_user_script/create_user_script.dart
  front/lib/screen/script/script_detail.dart
  front/lib/screen/script/script_list.dart
  front/lib/screen/setting/setting.dart
  front/lib/widget/record/read_record_script.dart
  front/lib/widget/script/read_script.dart
  front/lib/widget/script/script_list_tile.dart
Labels: enhancement

#51 [CD-172] GPT 코드에 LangChain 프롬프트 적용
  backend/create_script/config/config.py
  backend/create_script/gpt/__init__.py
  backend/requirements.txt
  front/lib/main.dart
  front/lib/model/load_data.dart
  front/lib/screen/script/create_user_script/adjust_user_script.dart
  front/lib/screen/script/create_user_script/create_user_script.dart
  front/lib/screen/script/script_detail.dart
  front/lib/screen/script/script_list.dart
  front/lib/screen/setting/setting.dart
  front/lib/widget/record/read_record_script.dart
  front/lib/widget/script/read_script.dart
  front/lib/widget/script/script_list_tile.dart
Labels: enhancement

#45 [CD-81] Feat: 홈화면 제작
  front/android/app/build.gradle
  front/android/app/src/main/AndroidManifest.xml
  front/assets/images/characters/carrot.png
  front/assets/images/characters/catus.png
  front/assets/images/characters/chick.png
  front/assets/images/characters/unicorn.png
  front/assets/wavs/guide_voice.wav
  front/ios/Flutter/AppFrameworkInfo.plist
  front/ios/Podfile
  front/ios/Podfile.lock
  front/ios/Runner.xcodeproj/project.pbxproj
  front/ios/Runner.xcodeproj/xcshareddata/xcschemes/Runner.xcscheme
  front/ios/Runner.xcworkspace/contents.xcworkspacedata
  front/ios/Runner/Info.plist
  front/lib/constants/color.dart
  front/lib/constants/fonts.dart
  front/lib/constants/image.dart
  front/lib/constants/text.dart
  front/lib/main.dart
  front/lib/model/load_data.dart
  front/lib/model/practice.dart
  front/lib/model/save_data.dart
  front/lib/model/user.dart
  front/lib/screen/bottom_navigation.dart
  front/lib/screen/home/home.dart
  front/lib/screen/my_record/my_record.dart
  front/lib/screen/script/script_list.dart
  front/lib/screen/sign_up/audio_player.dart
  front/lib/screen/sign_up/audio_recoder.dart
  front/lib/screen/sign_up/controller/user_controller.dart
  front/lib/screen/sign_up/get_user_voice.dart
  front/lib/widget/audio_player.dart
  front/lib/widget/audio_recoder/audio_recorder.dart
  front/lib/widget/audio_recoder/platform/audio_recoder_platform.dart
  front/lib/widget/audio_recoder/platform/audio_recorder_io.dart
  front/lib/widget/audio_recoder/recoder_controller.dart
  front/lib/widget/audio_recoder/recoding_sheet.dart
  front/lib/widget/audio_recoder/recording_section.dart
  front/lib/widget/home/attendanceStreak.dart
  front/lib/widget/home/attendance_streak.dart
  front/lib/widget/home/character_section.dart
  front/lib/widget/script/read_script.dart
  front/lib/widget/script/script_list_tile.dart
  front/pubspec.lock
  front/pubspec.yaml
Labels: enhancement

#57 [CD-166] 사용자 음성, 텍스트를 받아 가이드 음성 생성
  backend/_samples/README.md
  backend/feedback/text/__init__.py
  backend/main.py
  backend/requirements.txt
  backend/text/README.md
  backend/text/__init__.py
  backend/text/cleaners.py
  backend/text/en_numbers.py
  backend/text/ko_dictionary.py
  backend/text/korean.py
  backend/text/symbols.py
  backend/tts/LICENSE
  backend/tts/README.md
  backend/tts/__init__.py
  backend/tts/commons.py
  backend/tts/config/nia22.json
  backend/tts/data_utils.py
  backend/tts/models.py
  backend/tts/monotonic_align/__init__.py
  backend/tts/monotonic_align/core.c
  backend/tts/monotonic_align/core.pyx
  backend/tts/monotonic_align/setup.py
  backend/tts/utils.py
  backend/voice_converison/SPK014KBSCU004F002.wav
  backend/voice_converison/SPK064KBSCU001M001.wav
  backend/voice_converison/__init__.py
  backend/voice_converison/examples/knnvc_demo.ipynb
Labels: enhancement

#62 [CD-167] 만들어진 API 가져와서 음성 데이터 주고 받고 피드백 결과 Flutter 단에서 확인
  backend/main.py
  backend/tts/__init__.py
Labels: to master

#66 Hotifx: prevent a negative similarity
  backend/feedback/levenshtein/__init__.py
  backend/requirements.txt
Labels: bug
